builds:
  - binary: git-credential-op
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.buildCommit={{ .Commit }}
      - -X main.buildVersion={{ .Version }}
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - '^test:'
#       - '^docs:'
