name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        go: ['1.19']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true
      - run: go test -v -covermode=count -coverprofile=cover.out ./...
